local:
  output_dir: C:\Users\ndeas\Desktop\Columbia\Research\Abstract-Contrastive-Opinion-Summarization\data\twitter_data
  save_format: 'csv'
twitter:
  account:
    bearer_token: 'AAAAAAAAAAAAAAAAAAAAAHDjhAEAAAAAvdmg1c6blc9c8F0EzIBLlCsCoO0%3D3hJAvC5ijOhjLs6K8aM80LxGWeguyVvLkDejR2ZrVBBoO5iNYX'
  query_params:
    expansions:
      - referenced_tweets.id
      - referenced_tweets.id.author_id
      - author_id
      - attachments.media_keys
    media_fields:
      - media_key
      - type
      - url
      - duration_ms
      - height
      - width
      - preview_image_url
      - public_metrics
    tweet_fields:
      - author_id
      - conversation_id
      - created_at
      - in_reply_to_user_id
      - lang
      - public_metrics
      - possibly_sensitive
      - referenced_tweets
      - reply_settings
      - source
      - text
      - withheld
    user_fields:
      - created_at
      - description
      - id
      - name
      - public_metrics
      - username
      - pinned_tweet_id